spring:
  application:
    name: RestaurantManagement

  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration

  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  mail:
    host: smtp.gmail.com
    port: 587
    username: your_email@gmail.com
    password: your_app_password
    from: noreply@restaurantmanagement.com
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
        debug: false

  flyway:
    baseline-description: true
    baseline-on-migrate: true
    baseline-version: 1

server:
  port: 8080

logging:
  level:
    org.springframework.mail: INFO
    com.springboot.restaurantmanagement: DEBUG
