CREATE TABLE customer
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name         VARCHAR(255),
    phone_number VARCHAR(255),
    email        VARCHAR(255),
    created_at   TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_customer PRIMARY KEY (id)
);

CREATE TABLE drinks_management
(
    id       BIGINT           NOT NULL,
    weight   INTEGER          NOT NULL,
    volume   DOUBLE PRECISION NOT NULL,
    category VARCHAR(255),
    CONSTRAINT pk_drinks_management PRIMARY KEY (id)
);

CREATE TABLE food_management
(
    id       BIGINT NOT NULL,
    category VARCHAR(255),
    CONSTRAINT pk_food_management PRIMARY KEY (id)
);

CREATE TABLE menu
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name       VARCHAR(255),
    price      DOUBLE PRECISION                        NOT NULL,
    status     VARCHAR(255),
    restaurant BIGINT,
    CONSTRAINT pk_menu PRIMARY KEY (id)
);

CREATE TABLE order_item
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    quantity     INTEGER                                 NOT NULL,
    order_id     BIGINT,
    menu_item_id BIGINT,
    CONSTRAINT pk_order_item PRIMARY KEY (id)
);

CREATE TABLE order_management
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    customer     BIGINT,
    order_date   TIMESTAMP WITHOUT TIME ZONE,
    order_status VARCHAR(255),
    CONSTRAINT pk_order_management PRIMARY KEY (id)
);

CREATE TABLE restaurant
(
    id      BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name    VARCHAR(255),
    address VARCHAR(255),
    phone   VARCHAR(255),
    rating  FLOAT                                   NOT NULL,
    status  VARCHAR(255)                            NOT NULL,
    CONSTRAINT pk_restaurant PRIMARY KEY (id)
);

ALTER TABLE drinks_management
    ADD CONSTRAINT FK_DRINKS_MANAGEMENT_ON_ID FOREIGN KEY (id) REFERENCES menu (id);

ALTER TABLE food_management
    ADD CONSTRAINT FK_FOOD_MANAGEMENT_ON_ID FOREIGN KEY (id) REFERENCES menu (id);

ALTER TABLE menu
    ADD CONSTRAINT FK_MENU_ON_RESTAURANT FOREIGN KEY (restaurant) REFERENCES restaurant (id);

ALTER TABLE order_item
    ADD CONSTRAINT FK_ORDER_ITEM_ON_MENU_ITEM FOREIGN KEY (menu_item_id) REFERENCES menu (id);

ALTER TABLE order_item
    ADD CONSTRAINT FK_ORDER_ITEM_ON_ORDER FOREIGN KEY (order_id) REFERENCES order_management (id);

ALTER TABLE order_management
    ADD CONSTRAINT FK_ORDER_MANAGEMENT_ON_CUSTOMER FOREIGN KEY (customer) REFERENCES customer (id);