name: Docker Hub CI/CD and Render Deployment

on:
  push:
    branches:
      - deployment

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Check out the repository
      - name: Checkout code
        uses: actions/checkout@v4

      # Set up Java (JDK 21)
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: 'temurin'

      # Build the Spring Boot API application
      - name: Build with Maven
        run: |
          chmod +x ./mvnw
          ./mvnw clean package -DskipTests -e -X

      # Debug: List target directory
      - name: List target directory
        run: ls -l target

      # Save the build artifact for the next job
      - name: Save build artifact
        uses: actions/upload-artifact@v4
        with:
          name: RestaurantManagement
          path: RestaurantManagement/crud-*.jar  # Use a wildcard to match the JAR file

  docker:
    runs-on: ubuntu-latest
    needs: build

    steps:
      # Check out the repository
      - name: Checkout code
        uses: actions/checkout@v4

      # Download the build artifact from the previous job
      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          name: RestaurantManagement
          path: target

      # Login to Docker Hub
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      # Build and push Docker image
      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: |
            ${{ secrets.DOCKER_HUB_USERNAME }}/restaurant-management:latest
            ${{ secrets.DOCKER_HUB_USERNAME }}/restaurant-management:${{ github.sha }}